name: Build Android

on:
  push:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk
        pip install buildozer cython

    - name: Build DEBUG APK
      if: github.ref == 'refs/heads/main'
      run: buildozer android debug

    - name: Build RELEASE AAB
      if: github.ref == 'refs/heads/release'
      run: buildozer android release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: bin/