name: Build Android

on:
  push:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-pip \
          openjdk-17-jdk \
          zip \
          unzip \
          git \
          build-essential \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev

    - name: Install Python Dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Accept Android SDK Licenses
      run: yes | sdkmanager --licenses

    - name: Install Android SDK Packages
      run: |
        sdkmanager "platform-tools"
        sdkmanager "platforms;android-34"
        sdkmanager "build-tools;37.0.0"

    - name: Build DEBUG APK
      if: github.ref == 'refs/heads/main'
      run: buildozer android debug

    - name: Build RELEASE AAB
      if: github.ref == 'refs/heads/release'
      run: buildozer android release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: bin/